spring.application.name=DinosaurPark

park.max.capacity=150
park.admission=20.0
park.CentralHub.capacity=50
park.BathroomZone.capacity=10
park.BathroomZone.price=5.0
park.PowerPlantCost.DailyOperativeCost=100
park.ObservationCarnivore.cost=50.0
park.ObservationCarnivore.capacity=15
park.ObservationHerbivore.cost=30.0
park.ObservationHerbivore.capacity=20
park.simulation.totalSteps=100
park.bathroom.useDurationSteps=3
